### ISSUE TITLE
Cutefetch Look broken

### ISSUE THREAD

**Issue by FeyRetro** [cybardev/cutefetch#3]
Hello, is there any possible fix for this issue? I didn't tamper with source code, What I do after downloading the script is copied it to my home bin folder. 

Distro : Zorin OS 16.1 Lite
Terminal : xfce4-terminal
Shell : zsh

![image](https://user-images.githubusercontent.com/95857220/170904773-0aac9582-1d9c-4a07-b0df-aae0bf03dd9a.png)

**Comment by cybardev** [comment]
Looks like I messed up the icons on Linux. Thanks for pointing it out. Will fix it soon.

**Comment by cybardev** [comment]
@FeyRetro Give this [updated script](https://github.com/cybardev/cutefetch/blob/fix-linux-icons/cutefetch) a try. Let me know if that solves it.

**Comment by FeyRetro** [comment]
I tried the updated script in bash, it's worked. But in zsh, it's kinda work, The symbol appear but has "$" symbol on the end, and it has no color

![image](https://user-images.githubusercontent.com/95857220/171069591-a5ede0f3-8fbd-4322-a3d5-b9a730039425.png)
This one using `bash cutefetch`

![image](https://user-images.githubusercontent.com/95857220/171069634-acf5ee88-96bc-4608-be42-41c8ab689498.png)
Then this one with only `cutefetch`, Since I use zsh as default shell.

I think it's the zsh issue but i'm not sure

**Comment by cybardev** [comment]
@FeyRetro Could you try changing the first line from `#!/bin/sh` to `#!/usr/bin/env bash` and see if that works?

**Comment by FeyRetro** [comment]
> 

![image](https://user-images.githubusercontent.com/95857220/171072964-44d9db31-ff28-4449-9723-f1c3744de300.png)

So I do what you told me and it's work perfectly, I only typed `cutefetch` without `bash`
Thanks so much for the fix, should I close the issue or you have anything to say?

**Comment by cybardev** [comment]
Nope, that's all. Thanks for the issue.

I'll close the issue myself after merging pull request #4
