### ISSUE TITLE
resolution not available

### ISSUE THREAD

**Issue by yogeshdcool** [cybardev/cutefetch#5]
It was working fine some time ago but now I'm not able to get any output for `xdpyinfo | grep 'dimensions' |  grep -o '[0-9]+x[0-9]+'  | head -n 1`

I think some update to xdpyinfo changes the format of output so should I change the regex

**Comment by yogeshdcool** [comment]
adding -E to the second grep command fixes the issue
`xdpyinfo | grep 'dimensions' | grep -oE '[0-9]+x[0-9]+' | head -n 1`

**Comment by cybardev** [comment]
That is indeed my bad. I always alias `grep` to be `grep -E`, so I completely missed it.

Would you like to make a PR with the changes, or should I just update and push?

**Comment by yogeshdcool** [comment]
> Would you like to make a PR with the changes, or should I just update and push?
I'd love to give a PR
and thanks for this awesome script

**Comment by cybardev** [comment]
Marvelous. It looks good; thanks for the work.

I'll test it out and merge when I get to my Linux machine.

---

> thanks for this awesome script

You're welcome 😊 It fills me with great joy that other people are using it. Let me know if you see any other issues.
